### ISSUE TITLE
Status of android compatibility

### ISSUE THREAD

**Issue by Hannnes1** [nmfisher/thermion#29]
Hi,
We are using this plugin in an app that we are hoping to release to production within the next few weeks.

I realize that you are still actively developing a lot of features, and I don't want to pressure you more than I already do. I'm therefore wondering what the most stable branch/commit is. `develop` seems to work great for iOS, that doesn't work for Android as you mentioned in another issue.

Thank you!

Edit:
`2ed2e7f` (The commit before merging `feature/instancing` seems to be the latest commit that works on Android. Curious what you think?

**Comment by nmfisher** [comment]
That's great to hear. 

My suggestion would be to wait a week or so to let me merge in my recent work.

Just for background, recently I've been working on the `native-assets` branch for: 
1) decoupling the Flutter-only components from the Dart-only components
2) using the Dart `native-assets` build system for building/linking 
3) standardizing on Filament v1.51.2 for all platforms
4) web support  
5) some miscellaneous animation components

The good thing about (1) and (2) is that it will let me publish properly versioned packages to `pub.dev` (the downside is there will be some breaking changes that will require renaming a few things here and there in your code).

That work is mostly done now, I just need to rebuild Windows & check if an old upstream bug in Filament has been fixed.

I was planning to merge this into both `develop` and `master` soon (probably next week) and tag as a new 'release' (though the actual pub.dev release would still need longer, because I'd need to add the script for checking the library cache for the target platform and downloading if the prebuilt Filament library is not found).

**Comment by Hannnes1** [comment]
Great news!
Breaking changes are totally fine. Looking forward to testing out the new stuff!

**Comment by nmfisher** [comment]
@Hannnes1 this is all now merged in (and published to pub.dev, thanks again for your assistance with that!)

As I mentioned elsewhere, there's been some API changes, but if you [follow the quickstart documentation](https://docs.page/nmfisher/thermion/quickstart), that should help you with the migration.

I've tested this locally with my Android device in debug/release mode. If you don't experience any problems, please feel free to close this issue.

**Comment by Hannnes1** [comment]
Thank you. As far as I can tell, this works without any issues!
